"""added media to chats

Revision ID: 3fea1acabb3a
Revises: aecb51a3786c
Create Date: 2023-12-21 13:14:30.922545

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3fea1acabb3a'
down_revision = 'aecb51a3786c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_media',
    sa.Column('secret', sa.String(length=36), nullable=False),
    sa.Column('url', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'DOCUMENT', name='mediatype'), nullable=False),
    sa.Column('chat_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_media')
    # ### end Alembic commands ###
