"""Made lastname optional

Revision ID: 547068f5ddda
Revises: 4cb13b2692a5
Create Date: 2023-10-29 22:50:31.425454

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '547068f5ddda'
down_revision = '4cb13b2692a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=30),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=30),
               nullable=False)

    # ### end Alembic commands ###
