# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: Quality Assurance

on:
  pull_request:
    branches: [ dev ]

permissions: write-all


jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.5
      - name: Install project
        run: |
          python -m pip install pipenv
          pipenv install --dev
      - name: Run linter
        run: make lint
  tests:
    needs: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.5
      - name: Install project
        run: |
          python -m pip install pipenv
          pipenv install --dev
      - name: Run tests
        run: make test
        env:
          FLASK_SECRET_KEY: testing
          FLASK_SQLALCHEMY_DATABASE_URI: sqlite:///testing.db
          FLASK_REDIS_URL: ${{secrets.REDIS_URL}}
          FLASK_CELERY_BROKER_URL: ${{secrets.REDIS_URL}}
          FLASK_CELERY_RESULT_BACKEND: ${{secrets.REDIS_URL}}
  automerge:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: merge
          MERGE_COMMIT_MESSAGE: ${{ github.event.pull_request.title }}
          MERGE_DELETE_BRANCH: true
          PULL_REQUEST: ${{ github.event.number }}
